llm: openai          # claude | openai | gemini
model: gpt-4o        # model name for the active llm provider
issue_tracker: zoho_sprints  # zoho_sprints | jira | linear
version_control: github      # github | gitlab | azure_devops
notification: teams          # teams | slack | discord
cloud: aws

default_repos:
  - TV2Z-IND/wlb_api
default_branch: master
