from core.constants import ZohoStatus
from core.exceptions import DuplicatePRError
from core.models.pr import PRModel


def _zoho_link(issue_id: str) -> str:
    team_id = issue_id.split("|")[0] if "|" in issue_id else ""
    item_id = issue_id.split("|")[1] if "|" in issue_id else issue_id
    return f"https://sprints.zoho.com/team/{team_id}#itemdetails/{item_id}"


async def run(context: dict) -> dict:
    issue = context["issue"]
    fix = context["fix"]
    adapters = context["adapters"]
    vc = adapters["version_control"]
    issue_tracker = adapters["issue_tracker"]
    notification = adapters["notification"]
    work_type = context.get("work_type", "bugfix")

    repo = issue.affected_repos[0] if issue.affected_repos else ""
    branch = f"autofix/{issue.id.replace('|', '-')}"

    open_prs = vc.get_open_prs(repo)
    for existing in open_prs:
        if (existing.get("head", {}).get("ref") == branch
                or existing.get("source_branch") == branch):
            raise DuplicatePRError(f"PR already open for branch {branch}")

    commit_prefix = "feat" if work_type == "feature" else "fix"
    vc.create_branch(repo, branch, issue.target_branch)
    vc.commit_changes(repo, branch, fix.file_contents,
                      f"{commit_prefix}: auto-{'implement' if work_type == 'feature' else 'fix'} for task {issue.id}")

    reviewer = ""
    for path in fix.files_changed[:1]:
        blame = vc.get_blame(repo, path)
        reviewer = blame.get("login", "")
        if reviewer:
            break

    zoho_url = _zoho_link(issue.id)

    if work_type == "feature":
        label = "Feature Implementation"
        detail_header = "**Feature Summary:**"
        test_header = "**Tests:**"
        pr_title = f"[AutoFix] feat: {issue.title}"
    else:
        label = "Bug Fix"
        detail_header = "**Root Cause:**"
        test_header = "**Regression Test:**"
        pr_title = f"[AutoFix] {issue.title}"

    body = (
        f"## {label} — Zoho Task [{issue.id}]({zoho_url})\n\n"
        f"{detail_header}\n{fix.reasoning}\n\n"
        f"**Files Changed:** {', '.join(fix.files_changed)}\n\n"
        f"**Confidence:** {fix.confidence_score:.0%}\n\n"
        f"{test_header}\n```python\n{fix.regression_test}\n```\n\n"
        f"**Rollback:** Revert this PR — `git revert HEAD`\n\n"
        f"> :robot: Generated by AutoFix AI — review carefully before merging."
    )

    pr = vc.create_pr(PRModel(
        title=pr_title,
        body=body,
        branch_name=branch,
        base_branch=issue.target_branch,
        repo=repo,
        reviewer=reviewer,
        zoho_issue_id=issue.id,
        draft=True,
    ))

    issue_tracker.update_status(issue.id, ZohoStatus.FIX_PROPOSED)
    issue_tracker.post_comment(
        issue.id,
        f"Auto-{'implementation' if work_type == 'feature' else 'fix'} PR created: {pr.url}\n"
        "Please review the proposed changes.",
    )
    notification.send_message(
        "",
        f"{'Feature' if work_type == 'feature' else 'Fix'} PR ready for {issue.id}: "
        f"{pr.url} — reviewer: @{reviewer or 'unassigned'}",
    )

    return {**context, "pr": pr}
