from core.constants import ZohoStatus
from core.exceptions import DuplicatePRError
from core.models.pr import PRModel


async def run(context: dict) -> dict:
    issue = context["issue"]
    fix = context["fix"]
    adapters = context["adapters"]
    vc = adapters["version_control"]
    issue_tracker = adapters["issue_tracker"]
    notification = adapters["notification"]

    repo = issue.affected_repos[0] if issue.affected_repos else ""
    branch = f"autofix/{issue.id}"

    open_prs = vc.get_open_prs(repo)
    for existing in open_prs:
        if (existing.get("head", {}).get("ref") == branch
                or existing.get("source_branch") == branch):
            raise DuplicatePRError(f"PR already open for branch {branch}")

    vc.create_branch(repo, branch, issue.target_branch)
    vc.commit_changes(repo, branch, fix.file_contents, f"fix: auto-fix for issue {issue.id}")

    reviewer = ""
    for path in fix.files_changed[:1]:
        blame = vc.get_blame(repo, path)
        reviewer = blame.get("login", "")
        if reviewer:
            break

    body = (
        f"## Auto-Fix — Zoho Issue [{issue.id}](https://desk.zoho.com/agent/v1/ticket/{issue.id})\n\n"
        f"**Root Cause:**\n{fix.reasoning}\n\n"
        f"**Files Changed:** {', '.join(fix.files_changed)}\n\n"
        f"**Confidence:** {fix.confidence_score:.0%}\n\n"
        f"**Regression Test:**\n```python\n{fix.regression_test}\n```\n\n"
        f"**Rollback:** Revert this PR — `git revert HEAD`\n\n"
        f"> :robot: Generated by AutoFix AI — review carefully before merging."
    )

    pr = vc.create_pr(PRModel(
        title=f"[AutoFix] {issue.title}",
        body=body,
        branch_name=branch,
        base_branch=issue.target_branch,
        repo=repo,
        reviewer=reviewer,
        zoho_issue_id=issue.id,
        draft=True,
    ))

    issue_tracker.update_status(issue.id, ZohoStatus.FIX_PROPOSED)
    issue_tracker.post_comment(issue.id, f"Auto-fix PR created: {pr.url}\nPlease review the proposed changes.")
    notification.send_message("", f"PR ready for issue {issue.id}: {pr.url} — reviewer: @{reviewer or 'unassigned'}")

    return {**context, "pr": pr}
